### ISSUE TITLE
Linq4j and Java SE 6

### ISSUE THREAD

**Issue by codestream** [julianhyde/linq4j#3]
Hello. I've downloaded your project but stuck with build it. I am using Java SE6 and cannot build it. So, how is it possible to use this project without having to install Java 7 ?

**Comment by julianhyde** [comment]
It only runs on JDK7 and above. This project needs to use the latest JDK features.

In fact I want to use lambdas being developed in JDK8 so we will move to JDK8 only as soon as JDK8 is mature enough.

Give JDK7 a try. It is faster than JDK6. It's not difficult to install multiple JDKs on the same machine.
